filebeat.inputs:
- type: log
  enabled: true
  paths:
    - D:\MOD-Security_LOG\*.log
#    input_type: log
#    close_removed : false
#    clean_removed : false                 
#    ignore_older: 47h
#    clean_inactive: 48h
#  fields_under_root: true
  fields:
    event.module: modsecurity
    event.dataset: modsecurity.json

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
  
setup.template.settings:
  index.number_of_shards: 1
  
#setup.kibana:
#output.logstash:
#   The Logstash hosts
#  hosts: ["cloud.remotesyslog.com:22222"]
#output.elasticsearch:
#  hosts: ["cloud.remotesyslog.com:9200"]

output.logstash:
  hosts: ["cloud.remotesyslog.com:5045"]
#  ssl.enabled: true
#  ssl.certificate_authorities: ["${path.config}/cacert.crt"]

processors:
  - add_fields:
       target: organization
       fields:
          name: RS-Productie
  - add_host_metadata: ~
  - add_cloud_metadata: ~

setup.template.fields: ${path.config}/fields.yml
setup.template.json.enabled: false
setup.template.overwrite: true